### Vektor Ortogonal

In [13]:
import numpy as np


In [14]:
# buat vector i dengan elemen (1,0) dan vector j dengan elemen (0,1)
i = np.array([1, 0])
i

array([1, 0])

In [15]:
j = np.array([0, 1])
j

array([0, 1])

In [16]:
# buktikan bahwa vector i dan vector j itu orthogonal
np.dot(i, j)

np.int64(0)

### Bagaimana dengan vektor yang lain?

In [25]:
# buat vector i dengan elemen (1,2) dan vector j dengan elemen (2, -1)
v = np.array([1, 2])
v

array([1, 2])

In [24]:
w = np.array([2, -1])
w

array([ 2, -1])

In [27]:
# Bagaimana dengan v=(1,2) dan w=(2,-1), apakah juga orthogonal?
np.dot(v, w)

np.int64(0)