### Matrix menggunakan NumPy

In [1]:
import numpy as np

In [2]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[77,7], [7, 77], [70, 7]])
X

array([[77,  7],
       [ 7, 77],
       [70,  7]])

In [3]:
# tampilkan ukuran dari matrix X
X.shape

(3, 2)

In [4]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([77,  7, 70])

In [6]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([ 7, 77])

### Matrix menggunakan PyTorch

In [7]:
import torch

In [9]:
# ulangi soal nomor 1 menggunakan pytorch
X_pt = torch.tensor([[77,7], [7, 77], [70, 7]])
X_pt

tensor([[77,  7],
        [ 7, 77],
        [70,  7]])

In [10]:
X_pt.shape

torch.Size([3, 2])

In [11]:
X_pt[1,:]

tensor([ 7, 77])

### Matrix menggunakan TensorFlow

In [12]:
import tensorflow as tf

In [13]:
# ulangi soal nomor 1 menggunakan tensorflow
X_tf = tf.Variable([[77,7], [7, 77], [70, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[77,  7],
       [ 7, 77],
       [70,  7]], dtype=int32)>

In [14]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [15]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [16]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 77], dtype=int32)>