### Vektor

In [ ]:
import numpy as np

In [ ]:
# buat vector x dengan ukuran 3x1
x = np.array([77, 7, 7])
x

array([77,  7,  7])

In [ ]:
# hitung panjang vector x
len(x)

3

In [ ]:
# tampilkan ukuran vector x
x.shape

(3,)

In [ ]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [ ]:
# akses elemen pertama dari vector x
x[0]

np.int64(77)

In [ ]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

### Vektor Transpose

In [ ]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([77,  7,  7])

In [ ]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [ ]:
# buat vector y dengan ukuran 3x1
y = np.array([[75, 7, 5]])
y

array([[75,  7,  5]])

In [ ]:
# tampilkan ukuran vector y
y.shape

(1, 3)

In [ ]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y_t = y.T
y_t

array([[75],
       [ 7],
       [ 5]])

In [ ]:
# tampilkan ukuran dari vector y_t
y_t.shape

(3, 1)

### Vectors in PyTorch and TensorFlow

In [ ]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf


In [ ]:
x_pt = torch.tensor([77, 7, 7])
x_pt

tensor([77,  7,  7])

In [ ]:
x_tf = tf.Variable([77, 7, 7])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([77,  7,  7], dtype=int32)>